name: Gist Proxy API

on:
  workflow_dispatch:

jobs:
  fetch-gists:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Gists
        run: |
          curl -H "Authorization: token ${{ secrets.GIST_TRIGGER_PAT }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/gists > gists.json

      - name: Upload Gist Data
        uses: actions/upload-artifact@v3
        with:
          name: gist-data
          path: gists.json