name: Deploy Gist Proxy

on:
  push:
    branches:
      - gh-pages  # ✅ Make sure this runs on gh-pages branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Gist Proxy JSON
        run: |
          echo "{ \"GIST_TRIGGER_PAT\": \"${{ secrets.GIST_TRIGGER_PAT }}\" }" > gist-proxy.json

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:  # ✅ Add this line
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4