name: Deploy Gist Proxy

on:
  push:
    branches:
      - gh-pages  # ✅ Ensure this runs on gh-pages branch
  workflow_dispatch:  # ✅ Allow manual triggering

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages  # ✅ Ensure this checks out the correct branch

      - name: Create Gist Proxy JSON
        run: |
          echo "{ \"GIST_TRIGGER_PAT\": \"${{ secrets.GIST_TRIGGER_PAT }}\", \"OPENAI_API_KEY\": \"${{ secrets.OPENAI_API_KEY }}\" }" > gist-proxy.json
          cat gist-proxy.json  # Debugging: Print the file to check contents
        env:
          GIST_TRIGGER_PAT: ${{ secrets.GIST_TRIGGER_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages  # ✅ Ensure this matches GitHub Pages environment
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
